#############################################################################
# Makefile for building: FutoshikiSolver.app/Contents/MacOS/FutoshikiSolver
# Generated by qmake (3.0) (Qt 5.7.1)
# Project:  FutoshikiSolver.pro
# Template: app
# Command: /Users/hkunda/Qt/5.7/clang_64/bin/qmake -o Makefile FutoshikiSolver.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -O2 -std=gnu++11 -Wall -W -fPIC $(DEFINES) -g
INCPATH       = -I. -I. -I../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I../../Qt/5.7/clang_64/lib/QtGui.framework/Headers -I../../Qt/5.7/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../Qt/5.7/clang_64/mkspecs/macx-clang -F/Users/hkunda/Qt/5.7/clang_64/lib
QMAKE         = /Users/hkunda/Qt/5.7/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = FutoshikiSolver1.0.0
DISTDIR = /Users/hkunda/Projects/FutoshikiSolver/.tmp/FutoshikiSolver1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -stdlib=libc++ -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -mmacosx-version-min=10.8 -Wl,-rpath,/Users/hkunda/Qt/5.7/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/hkunda/Qt/5.7/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = exec.cpp \
		Grid.cpp \
		IneqButton.cpp \
		NumberButton.cpp \
		solver.cpp \
		SolverUI.cpp moc_Grid.cpp \
		moc_IneqButton.cpp \
		moc_NumberButton.cpp \
		moc_SolverUI.cpp
OBJECTS       = exec.o \
		Grid.o \
		IneqButton.o \
		NumberButton.o \
		solver.o \
		SolverUI.o \
		moc_Grid.o \
		moc_IneqButton.o \
		moc_NumberButton.o \
		moc_SolverUI.o
DIST          = ../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.7/clang_64/mkspecs/features/toolchain.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		FutoshikiSolver.pro Grid.h \
		IneqButton.h \
		NumberButton.h \
		solver.h \
		SolverUI.h exec.cpp \
		Grid.cpp \
		IneqButton.cpp \
		NumberButton.cpp \
		solver.cpp \
		SolverUI.cpp
QMAKE_TARGET  = FutoshikiSolver
DESTDIR       = 
TARGET        = FutoshikiSolver.app/Contents/MacOS/FutoshikiSolver


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d FutoshikiSolver.app/Contents/MacOS/ || mkdir -p FutoshikiSolver.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: FutoshikiSolver.pro ../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf ../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/qdevice.pri \
		../../Qt/5.7/clang_64/mkspecs/features/device_config.prf \
		../../Qt/5.7/clang_64/mkspecs/common/unix.conf \
		../../Qt/5.7/clang_64/mkspecs/common/mac.conf \
		../../Qt/5.7/clang_64/mkspecs/common/macx.conf \
		../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf \
		../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.7/clang_64/mkspecs/common/clang.conf \
		../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt/5.7/clang_64/mkspecs/qconfig.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf \
		../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt/5.7/clang_64/mkspecs/features/toolchain.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt/5.7/clang_64/mkspecs/features/default_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf \
		../../Qt/5.7/clang_64/mkspecs/features/qt.prf \
		../../Qt/5.7/clang_64/mkspecs/features/resources.prf \
		../../Qt/5.7/clang_64/mkspecs/features/moc.prf \
		../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt/5.7/clang_64/mkspecs/features/uic.prf \
		../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf \
		../../Qt/5.7/clang_64/mkspecs/features/yacc.prf \
		../../Qt/5.7/clang_64/mkspecs/features/lex.prf \
		FutoshikiSolver.pro \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile FutoshikiSolver.pro
../../Qt/5.7/clang_64/mkspecs/features/spec_pre.prf:
../../Qt/5.7/clang_64/mkspecs/qdevice.pri:
../../Qt/5.7/clang_64/mkspecs/features/device_config.prf:
../../Qt/5.7/clang_64/mkspecs/common/unix.conf:
../../Qt/5.7/clang_64/mkspecs/common/mac.conf:
../../Qt/5.7/clang_64/mkspecs/common/macx.conf:
../../Qt/5.7/clang_64/mkspecs/common/sanitize.conf:
../../Qt/5.7/clang_64/mkspecs/common/gcc-base.conf:
../../Qt/5.7/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.7/clang_64/mkspecs/common/clang.conf:
../../Qt/5.7/clang_64/mkspecs/common/clang-mac.conf:
../../Qt/5.7/clang_64/mkspecs/qconfig.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.7/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.7/clang_64/mkspecs/features/qt_functions.prf:
../../Qt/5.7/clang_64/mkspecs/features/qt_config.prf:
../../Qt/5.7/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt/5.7/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/5.7/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt/5.7/clang_64/mkspecs/features/toolchain.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/toolchain.prf:
../../Qt/5.7/clang_64/mkspecs/features/default_pre.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt/5.7/clang_64/mkspecs/features/resolve_config.prf:
../../Qt/5.7/clang_64/mkspecs/features/default_post.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt/5.7/clang_64/mkspecs/features/warn_on.prf:
../../Qt/5.7/clang_64/mkspecs/features/qt.prf:
../../Qt/5.7/clang_64/mkspecs/features/resources.prf:
../../Qt/5.7/clang_64/mkspecs/features/moc.prf:
../../Qt/5.7/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt/5.7/clang_64/mkspecs/features/uic.prf:
../../Qt/5.7/clang_64/mkspecs/features/unix/thread.prf:
../../Qt/5.7/clang_64/mkspecs/features/file_copies.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/rez.prf:
../../Qt/5.7/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Qt/5.7/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt/5.7/clang_64/mkspecs/features/exceptions.prf:
../../Qt/5.7/clang_64/mkspecs/features/yacc.prf:
../../Qt/5.7/clang_64/mkspecs/features/lex.prf:
FutoshikiSolver.pro:
../../Qt/5.7/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../Qt/5.7/clang_64/lib/QtGui.framework/QtGui.prl:
../../Qt/5.7/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile FutoshikiSolver.pro

qmake_all: FORCE

FutoshikiSolver.app/Contents/PkgInfo: 
	@test -d FutoshikiSolver.app/Contents || mkdir -p FutoshikiSolver.app/Contents
	@$(DEL_FILE) FutoshikiSolver.app/Contents/PkgInfo
	@echo "APPL????" > FutoshikiSolver.app/Contents/PkgInfo
FutoshikiSolver.app/Contents/Resources/empty.lproj: 
	@test -d FutoshikiSolver.app/Contents/Resources || mkdir -p FutoshikiSolver.app/Contents/Resources
	@touch FutoshikiSolver.app/Contents/Resources/empty.lproj
	
FutoshikiSolver.app/Contents/Info.plist: 
	@test -d FutoshikiSolver.app/Contents || mkdir -p FutoshikiSolver.app/Contents
	@$(DEL_FILE) FutoshikiSolver.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,com.kunda.codepath.FutoshikiSolver,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,FutoshikiSolver,g" -e "s,@LIBRARY@,FutoshikiSolver,g" -e "s,@TYPEINFO@,????,g" ../../Qt/5.7/clang_64/mkspecs/macx-clang/Info.plist.app >FutoshikiSolver.app/Contents/Info.plist

all: Makefile \
		FutoshikiSolver.app/Contents/PkgInfo \
		FutoshikiSolver.app/Contents/Resources/empty.lproj \
		FutoshikiSolver.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents Grid.h IneqButton.h NumberButton.h solver.h SolverUI.h $(DISTDIR)/
	$(COPY_FILE) --parents exec.cpp Grid.cpp IneqButton.cpp NumberButton.cpp solver.cpp SolverUI.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r FutoshikiSolver.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_Grid.cpp moc_IneqButton.cpp moc_NumberButton.cpp moc_SolverUI.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_Grid.cpp moc_IneqButton.cpp moc_NumberButton.cpp moc_SolverUI.cpp
moc_Grid.cpp: ../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		NumberButton.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qsize.h \
		IneqButton.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QIcon \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		Grid.h \
		../../Qt/5.7/clang_64/bin/moc
	/Users/hkunda/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/hkunda/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/hkunda/Projects/FutoshikiSolver -I/Users/hkunda/Projects/FutoshikiSolver -I/Users/hkunda/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/hkunda/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/hkunda/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/hkunda/Qt/5.7/clang_64/lib Grid.h -o moc_Grid.cpp

moc_IneqButton.cpp: ../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QIcon \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		IneqButton.h \
		../../Qt/5.7/clang_64/bin/moc
	/Users/hkunda/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/hkunda/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/hkunda/Projects/FutoshikiSolver -I/Users/hkunda/Projects/FutoshikiSolver -I/Users/hkunda/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/hkunda/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/hkunda/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/hkunda/Qt/5.7/clang_64/lib IneqButton.h -o moc_IneqButton.cpp

moc_NumberButton.cpp: ../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qsize.h \
		NumberButton.h \
		../../Qt/5.7/clang_64/bin/moc
	/Users/hkunda/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/hkunda/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/hkunda/Projects/FutoshikiSolver -I/Users/hkunda/Projects/FutoshikiSolver -I/Users/hkunda/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/hkunda/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/hkunda/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/hkunda/Qt/5.7/clang_64/lib NumberButton.h -o moc_NumberButton.cpp

moc_SolverUI.cpp: ../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QColor \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QComboBox \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		solver.h \
		Grid.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		NumberButton.h \
		IneqButton.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QIcon \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h \
		SolverUI.h \
		../../Qt/5.7/clang_64/bin/moc
	/Users/hkunda/Qt/5.7/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/hkunda/Qt/5.7/clang_64/mkspecs/macx-clang -I/Users/hkunda/Projects/FutoshikiSolver -I/Users/hkunda/Projects/FutoshikiSolver -I/Users/hkunda/Qt/5.7/clang_64/lib/QtWidgets.framework/Headers -I/Users/hkunda/Qt/5.7/clang_64/lib/QtGui.framework/Headers -I/Users/hkunda/Qt/5.7/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.0.0/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include -F/Users/hkunda/Qt/5.7/clang_64/lib SolverUI.h -o moc_SolverUI.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

exec.o: exec.cpp SolverUI.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QColor \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QComboBox \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		solver.h \
		Grid.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		NumberButton.h \
		IneqButton.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QIcon \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exec.o exec.cpp

Grid.o: Grid.cpp Grid.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		NumberButton.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qsize.h \
		IneqButton.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QIcon \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Grid.o Grid.cpp

IneqButton.o: IneqButton.cpp IneqButton.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QIcon \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IneqButton.o IneqButton.cpp

NumberButton.o: NumberButton.cpp NumberButton.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qsize.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o NumberButton.o NumberButton.cpp

solver.o: solver.cpp solver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o solver.o solver.cpp

SolverUI.o: SolverUI.cpp SolverUI.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QSize \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QColor \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qcolor.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QString \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QComboBox \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qcombobox.h \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/QStringList \
		../../Qt/5.7/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		solver.h \
		Grid.h \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/QGridLayout \
		../../Qt/5.7/clang_64/lib/QtWidgets.framework/Headers/qgridlayout.h \
		NumberButton.h \
		IneqButton.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QIcon \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qicon.h \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/QPixmap \
		../../Qt/5.7/clang_64/lib/QtGui.framework/Headers/qpixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SolverUI.o SolverUI.cpp

moc_Grid.o: moc_Grid.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Grid.o moc_Grid.cpp

moc_IneqButton.o: moc_IneqButton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_IneqButton.o moc_IneqButton.cpp

moc_NumberButton.o: moc_NumberButton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_NumberButton.o moc_NumberButton.cpp

moc_SolverUI.o: moc_SolverUI.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SolverUI.o moc_SolverUI.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

